[io]
# エクセルファイルへのフルパス
excel_path = E:\RyuTeX\hateruma_honda_wf.xlsx

# 語彙データのシート名
sheet_main = hateruma

# ある場合、例文のシート名
#sheet_example = reibun

[orthography]
profile = default

[orthography.default.replacements]
ZENKAKU_SPACE = \ws{}
LBRACKET = \josho{}
RBRACKET = \kako{}

[orthography.default.rules]
rule1 = [～〜] => \ntilde{}

[orthography.default.enclosures]
enc1 = ˩˥˥˥˩ ; tl

[sorting]
ignorable_chars = ゜-—‐–－[]˩˥ⓩ～〜ⓢ^

[output]
# ーあー、ーいーなどの出力
headletters = true
# auto/hiragana
headletter_mode = auto

# 語彙データシートにおける欄名
[headers.main]
id = 項目ID
mid = 意味ID
kana = 表記1
#kana2 = 表記3
ipa = 音声表記
pos = 品詞
rui = 類
para = 否定
biko = 備考
pitch = 型
filter = filter
order = 順
meaning = 意味
reading = 読み
ruby = ルビ
comment = 解説
#rei = 例

# （ある場合）例文シートにおける欄名
[headers.examples]
#mid = 意味ID
#kana = 表記1
#jptrsl = 訳
#filter = filter