[io]
# エクセルファイルへのフルパス
excel_path = .xlsx

# 語彙データのシート名
sheet_main = tarama

# ある場合、例文のシート名
sheet_example = reibun

[orthography]
profile = default

[orthography.default.replacements]
ZENKAKU_SPACE = \ws{}
LBRACKET = \josho{}
RBRACKET = \kako{}
゜ = \m{}
ⓢ = \sms{}
ⓩ = \smz{}

[orthography.default.rules]
rule1 = [～〜] => \ntilde{}

[sorting]
ignorable_chars = ゜-—‐–－[]～〜

[output]
# ーあー、ーいーなどの出力（true/false）
headletters = true
# auto: 仮名表記通り、hiragana：平仮名に
headletter_mode = auto

# 語彙データシートにおける欄名
[headers.main]
id = 項目ID
mid = 意味ID
kana = 表記1
#kana2 = 表記3
ipa = 表記2
pos = 品詞
rui = 活用
#para = 
biko = 備考
#pitch = 型
filter = filter
order = 順
meaning = 意味
#reading = 読み
ruby = ルビ
comment = 解説
#rei = 例

# （ある場合）例文シートにおける欄名
[headers.examples]
mid = 意味ID
kana = 表記1
jptrsl = 和訳
filter = filter