#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
tab2tex_v1.py

Convert RyuTab-formatted Excel data into TeX source for the RyuTeX template.

Outputs:
	\\entry{\\headPrint[...]}{\\MeaningsBlock{\\meaning{...}{...}{...}...}}{\\tailPrint[...]}
	(and optionally reverse-index entries via \\rentry)

Design principles:
- Source data (RyuTab) contains no TeX commands.
- All TeX is generated by this script.
- Escaping of TeX special characters is applied systematically to all input text.
- Ryukyuan orthographic normalization and ruby processing are handled explicitly by field type.

Text processing:
- Ryukyuan fields → escaped + orthography profile applied
- Japanese prose fields → escaped + embedded Ryukyuan (〈...〉) processed + ruby applied
- Ruby fields → escaped + ruby processing
- Plain Japanese fields → escaped only

Sorting and grouping principles:
- Entry sorting and headword grouping are not based on raw Unicode order.
- Sorting uses a hard-coded gojūon-based collation.
- Before sorting/grouping, kana strings are normalized in two layers:

  1. Core kana cleaning
	- remove whitespace
	- remove user-configurable ignorable characters
	- normalize small kana to full-size kana
	- remove voicing distinctions (e.g. は/ば/ぱ sort together)

  2. Script unification
	- convert katakana to hiragana for sorting/grouping only

- As a result, sorting/grouping intentionally conflates:
	- hiragana and katakana
	- small and full-size kana
	- voiced / semi-voiced and unvoiced kana

- Displayed headletters are derived separately from grouping keys:
	- in `auto` mode, core kana cleaning is applied but script is preserved
	- in `hiragana` mode, script is additionally unified to hiragana

- This means collation, grouping, and display are related but not identical operations.

Markup conventions in RyuTab:
- 〈...〉 : embedded Ryukyuan inside Japanese text
- ｜...〔...〕 / ...〔...〕 : ruby notation
- These are treated as structured markup, not literal characters

Notes:
- All key–value pairs are always braced: key={value}
  (ensures correct TeX parsing even when values contain commas)
- Validation of RyuTab format (including reserved characters and markup correctness)
  is expected to be performed separately.
- The current collation logic is intentionally hard-coded; more specialized section systems
  (e.g. custom handling of は/ば/ぱ or script-sensitive sectioning) would require a separate,
  explicitly configurable collation/section design.
"""

from __future__ import annotations

import os
import argparse
import configparser
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Dict, List, Optional, Pattern, Tuple

try:
	import pandas as pd
except ImportError:
	raise SystemExit(
		"Missing dependency: pandas\n"
		"\n"
		"Please install required packages from the command prompt:\n"
		"    python -m pip install -r tab2tex_requirements.txt\n"
	)
	
# -----------------------------
# Project-specific Settings
# -----------------------------

@dataclass
class Settings:
	excel_path: Path = Path()
	sheet_main: str = "goi"
	sheet_example: Optional[str] = None
	profile: str = ""
	ignorable_for_sort: str = ""
	headletters: bool = True
	headletter_mode: str = "auto"

def load_settings(path: str) -> tuple[Settings, HeaderMap, OrthoProfile]:
	cfg = configparser.ConfigParser()
	cfg.optionxform = str # Case-sensitive

	loaded = cfg.read(path, encoding="utf-8")
	if not loaded:
		raise ValueError(f"Settings file not found or unreadable: {path}")

	# Initialize an instance of the Settings class
	s = Settings()

	# strings
	if not cfg.has_option("io", "excel_path"):
		raise ValueError("Missing required setting: [io] excel_path")

	excel_path_raw = cfg.get("io", "excel_path").strip()

	if excel_path_raw == "":
		raise ValueError("Setting [io] excel_path is empty")

	excel_path = Path(excel_path_raw)

	if not excel_path.is_file():
		raise ValueError(f"Excel file not found or not a file: {excel_path}")

	s.excel_path = excel_path
		
	s.sheet_main = cfg.get("io", "sheet_main", fallback=s.sheet_main)
	s.sheet_example = cfg.get("io", "sheet_example", fallback=None) # Optional example sentence sheet
	s.profile = cfg.get("orthography", "profile", fallback="").strip()
	s.ignorable_for_sort = cfg.get("sorting", "ignorable_chars", fallback="")

	# headletters
	s.headletters = cfg.getboolean("output", "headletters", fallback=True)
	s.headletter_mode = cfg.get("output", "headletter_mode", fallback="auto").strip().lower()
	if s.headletter_mode not in {"auto", "hiragana"}:
		raise ValueError(
			f"Invalid [output] headletter_mode: {s.headletter_mode!r} "
			f"(expected 'auto' or 'hiragana')"
		)

	# load header map
	hmap = load_header_map(cfg)
	profile = load_ortho_profile(cfg, s.profile)

	return s, hmap, profile

# ---
# Header names
# semantic keys (stable)
H_ID = "id"
H_MID = "mid"
H_KANA = "kana"
H_KANA2 = "kana2"
H_IPA = "ipa"
H_POS = "pos"
H_RUI = "rui"
H_PARA = "para"
H_BIKO = "biko"
H_PITCH = "pitch"
H_FILTER = "filter"
H_ORDER = "order"
H_MEANING = "meaning"
H_READING = "reading"
H_RUBY = "ruby"
H_COM = "comment"
H_REI = "rei"

EX_MID = "mid"
EX_KANA = "kana"
EX_JPTRSL = "jptrsl"
EX_FILTER = "filter"

@dataclass(frozen=True)
class HeaderMap:
	main: Dict[str, str]
	ex: Dict[str, str]

def load_header_map(cfg: configparser.ConfigParser) -> HeaderMap:
	main = dict(cfg.items("headers.main")) if cfg.has_section("headers.main") else {}
	ex = dict(cfg.items("headers.examples")) if cfg.has_section("headers.examples") else {}
	return HeaderMap(main=main, ex=ex)

def require_cols_semantic(df, hmap: Dict[str, str], keys, sheetname: str) -> None:
	missing = []
	for k in keys:
		cname = hmap.get(k, "").strip()
		if cname == "" or cname not in df.columns:
			missing.append(f"{k} -> '{cname}'")
	if missing:
		raise ValueError(f"Missing required columns in {sheetname}: " + ", ".join(missing))

def get_cell_semantic(row, hmap: Dict[str, str], key: str) -> str:
	cname = hmap.get(key, "").strip()
	if cname == "" or cname not in row.index:
		return ""
	return get_cell(row, cname) 

def get_cell(row: pd.Series, col: str) -> str:
	if col not in row.index:
		return ""

	v = row[col]
	
	# Handle pandas NaN / None
	if pd.isna(v):
		return ""
	
	s = str(v)

	return s.strip()

# -----------------------------
# Orthographic Profile
# -----------------------------

SPECIAL_REPLACEMENT_KEYS = {
	"ZENKAKU_SPACE": "　",
	"SPACE": " ",
	"TAB": "\t",
	"CARET": "^",
	"LBRACKET": "[",
	"RBRACKET": "]",
}

# Kana orthography classes
@dataclass(frozen=True)
class NormRule:
	pat: Pattern[str]
	repl: str | Callable[[re.Match], str]

@dataclass(frozen=True)
class EnclosureRule:
	pat: Pattern[str]
	command: str

@dataclass(frozen=True)
class OrthoProfile:
	# literal replacements (fast, obvious)
	replacements: Dict[str, str]
	# regex rules (for tone runs, etc.)
	rules: List[NormRule]
	# Enclosure rules
	enclosures: List[EnclosureRule]

def load_ortho_profile(cfg: configparser.ConfigParser, name: str) -> OrthoProfile:
	base = f"orthography.{name}"
	repl_section = base + ".replacements"
	rules_section = base + ".rules"
	encl_section = base + ".enclosures"

	has_repl = cfg.has_section(repl_section)
	has_rules = cfg.has_section(rules_section)
	has_encl = cfg.has_section(encl_section)

	if not (has_repl or has_rules or has_encl):
		raise ValueError(
			f"Missing orthography profile definition for '{name}'. "
			f"Expected at least one of "
			f"[{repl_section}], [{rules_section}], or [{encl_section}]"
		)

	replacements = {}
	if has_repl:
		for k, v in cfg.items(repl_section):
			src = SPECIAL_REPLACEMENT_KEYS.get(k, k)
			replacements[src] = v

	rules = []
	if has_rules:
		for _, v in cfg.items(rules_section):
			if "=>" not in v:
				raise ValueError(
					f"Invalid orthography rule in [{rules_section}]: {v!r} "
					f"(expected: PATTERN => REPLACEMENT)"
				)
			pat_str, repl_str = map(str.strip, v.split("=>", 1))
			rules.append(NormRule(re.compile(pat_str), repl_str))

	enclosures = []
	if has_encl:
		for key, v in cfg.items(encl_section):
			if ";" not in v:
				raise ValueError(
					f"Invalid enclosure rule '{key}' in [{encl_section}]: {v!r} "
					f"(expected: SYMBOLS ; COMMAND)"
				)
			symbols_str, command = map(str.strip, v.split(";", 1))
			if not symbols_str:
				raise ValueError(
					f"Empty symbol list in enclosure rule '{key}' of [{encl_section}]"
				)
			if not command:
				raise ValueError(
					f"Empty command name in enclosure rule '{key}' of [{encl_section}]"
				)

			chars = "".join(dict.fromkeys(symbols_str))
			pat = re.compile("[" + re.escape(chars) + "]+")
			enclosures.append(EnclosureRule(pat=pat, command=command))

	return OrthoProfile(
		replacements=replacements,
		rules=rules,
		enclosures=enclosures
	)

# -----------------------------
# TeX / string helpers
# -----------------------------
_TEX_SPECIAL = re.compile(r'([%#$&_{}])')
_TEX_TILDE = re.compile(r'~')
_TEX_CARET = re.compile(r'\^')
_TEX_BACKSLASH = re.compile(r'\\')

def tex_escape(s: str) -> str:
	"""
	Conservative TeX escaping.
	Escapes all TeX special characters, including backslash.
	Assumes no raw TeX is present in input data.
	"""
	if s is None:
		return ""
	s = str(s)
	if s == "":
		return ""

	# Escape backslash first
	s = _TEX_BACKSLASH.sub(r'\\textbackslash{}', s)

	s = _TEX_SPECIAL.sub(r'\\\1', s)
	s = _TEX_TILDE.sub(r'\\textasciitilde{}', s)
	s = _TEX_CARET.sub(r'\\textasciicircum{}', s)

	return s

# --------------------
# Project-specific orthographic profile and normalization
# --------------------

# No case escape + general ruby

def render_ryu(s: str, profile: OrthoProfile) -> str:
	s = tex_escape(s or "")
	return tex_norm_custom(s, profile)

def render_jp_prose(s: str, profile: OrthoProfile) -> str:
	s = tex_escape(s or "")
	s = tex_embify_ryu(s, profile=profile) # Handles embedded Ryukyuan
	s = tex_rubyize_general(s)
	return s

def render_jp_ruby(s: str) -> str:
	s = tex_escape(s or "")
	return tex_rubyize(s) # rubyize already applies general ruby

def render_jp_plain(s: str) -> str:
	return tex_escape(s or "")


# Customizable normalization based on orthographic profile 
def tex_norm_custom(s: str, profile: OrthoProfile) -> str:
	"""
	Project-configurable normalization: apply literal replacements, then regex rules.
	"""
	if s is None:
		return ""
	s = str(s)
	if s == "":
		return ""

	# 1) literal replacements
	for src, dst in profile.replacements.items():
		s = s.replace(src, dst)

	# 2) regex rules
	for rule in profile.rules:
		if isinstance(rule.repl, str):
			s = rule.pat.sub(lambda m, repl=rule.repl: repl, s)
		else:
			s = rule.pat.sub(rule.repl, s)

	for enc in profile.enclosures:
		s = enc.pat.sub(
			lambda m: "\\" + enc.command + "{" + m.group(0) + "}",
			s
		)

	return s

# General pattern for converting ruby
# Allow ruby start at:
#   - BOS
#   - ｜ (consumed)
#   - 、 or 。 (kept)
#   - 、｜ or 。｜ (keep punctuation, consume bar)
_RE_RUBY_GENERAL = re.compile(
	r'(^|｜|、｜|。｜|、|。)'
	r'(?P<a>[^｜〔〕、。]+)'
	r'〔(?P<b>[^〕]+)〕'
)

def tex_rubyize_general(s: str) -> str:
	"""
	Convert strict ruby markup to TeX \\ruby[g]{...}{...}.

	Accepted starts:
	- 語〔ご〕            (BOS only)
	- ｜語〔ご〕          (bar consumed)
	- 、語〔ご〕 / 。語〔ご〕
	- 、｜語〔ご〕 / 。｜語〔ご〕 (punctuation kept; bar consumed)
	"""

	def _repl(m: re.Match) -> str:
		prefix = m.group(1)

		if prefix == "｜":
			prefix = ""
		elif prefix == "、｜":
			prefix = "、"
		elif prefix == "。｜":
			prefix = "。"

		return prefix + r'\ruby[g]{%s}{%s}' % (m.group('a'), m.group('b'))

	return _RE_RUBY_GENERAL.sub(_repl, s)

# Helper functions for converting ruby 

_RUBY_BOUNDARY = "\uE000"
_RE_RUBY = re.compile(
	r'(?P<a>[^。（）' + _RUBY_BOUNDARY + r']+)'  # GREEDY base
	r'（(?P<b>[^）]+)）'
)

# Ruby-specific column
def tex_rubyize(s: str) -> str:
	"""
	Convert in-cell ruby markup to TeX \\ruby[g]{...}{...}.

	Accepted patterns:
	- 語（ルビ）            -> \\ruby[g]{語}{ルビ}
	- 訳語（やくご）        -> \\ruby[g]{訳語}{やくご}
	- 訳（やく）語（ご）    -> \\ruby[g]{訳}{やく}\\ruby[g]{語}{ご}

	Explicit boundary:
	- （） blocks ruby span across the marker
	  引（ひ）っ（）提（さ）げる
	  -> \\ruby[g]{引}{ひ}っ\\ruby[g]{提}{さ}げる

	Multiple meanings / notes:
	- Ruby applies anywhere (not only sentence-initial)
	  （補足）訳語（やくご）。別（べつ）の意味
	  -> （補足）\\ruby[g]{訳語}{やくご}。\\ruby[g]{別}{べつ}の意味

	Rules:
	- Ruby base is greedy and never crosses （ ） 。 or （） boundaries
	- Empty ruby （） is removed after enforcing the boundary
	"""
	
	# Apply general ruby for nested parentheses
	s = tex_rubyize_general(s)
	
	# Convert explicit hard boundary
	s = re.sub(r'（\s*）', _RUBY_BOUNDARY, s)

	# rubyize
	s = _RE_RUBY.sub(r'\\ruby[g]{\g<a>}{\g<b>}', s)

	# remove boundary
	s = s.replace(_RUBY_BOUNDARY, '')

	return s

# Embify
_RE_EMB_RYU = re.compile(r'〈(?P<x>[^〉]*)〉')  # no nesting; deterministic

def tex_embify_ryu(s: str, profile: OrthoProfile) -> str:
	"""
	Convert embedded Ryukyuan marked as 〈...〉 into TeX \\emb{...},
	and apply tex_norm_custom() ONLY to the inside.

	Example:
	「...粟は〈アングル〉...」 -> 「...粟は\\emb{アングル}...」
	(with tex_norm_custom applied inside \\emb{...})
	"""
	if s is None:
		return ""

	def _repl(m: re.Match) -> str:
		inner = m.group("x")
		inner = tex_norm_custom(inner, profile)  # only inside gets project macros
		return r"\emb{" + inner + "}"

	return _RE_EMB_RYU.sub(_repl, s)

def keyval_pair(k: str, v: str) -> str:
	"""
	Build key=val for TeX keyval.
	"""
	v = v.strip()
	if v == "":
		return ""
	
	return f"{k}={{{v}}}"

# --------
# Sorting 
# --------

_WS_ANY = re.compile(r"[ \t\r\n　]+")   # ASCII + 全角スペース

_SMALL_TO_BIG = str.maketrans({
	# hiragana
	'ゃ': 'や', 'ゅ': 'ゆ', 'ょ': 'よ',
	'ぁ': 'あ', 'ぃ': 'い', 'ぅ': 'う', 'ぇ': 'え', 'ぉ': 'お',
	'っ': 'つ',
	'ゎ': 'わ',

	# katakana
	'ャ': 'ヤ', 'ュ': 'ユ', 'ョ': 'ヨ',
	'ァ': 'ア', 'ィ': 'イ', 'ゥ': 'ウ', 'ェ': 'エ', 'ォ': 'オ',
	'ッ': 'ツ',
	'ヮ': 'ワ',
})

_SEION_MAP = {
	"ゔ": "う",
	"が": "か", "ぎ": "き", "ぐ": "く", "げ": "け", "ご": "こ",
	"ざ": "さ", "じ": "し", "ず": "す", "ぜ": "せ", "ぞ": "そ",
	"だ": "た", "ぢ": "ち", "づ": "つ", "で": "て", "ど": "と",
	"ば": "は", "び": "ひ", "ぶ": "ふ", "べ": "へ", "ぼ": "ほ",
	"ぱ": "は", "ぴ": "ひ", "ぷ": "ふ", "ぺ": "へ", "ぽ": "ほ",
	"ガ": "カ", "ギ": "キ", "グ": "ク", "ゲ": "ケ", "ゴ": "コ",
	"ザ": "サ", "ジ": "シ", "ズ": "ス", "ゼ": "セ", "ゾ": "ソ",
	"ダ": "タ", "ヂ": "チ", "ヅ": "ツ", "デ": "テ", "ド": "ト",
	"バ": "ハ", "ビ": "ヒ", "ブ": "フ", "ベ": "ヘ", "ボ": "ホ",
	"パ": "ハ", "ピ": "ヒ", "プ": "フ", "ペ": "ヘ", "ポ": "ホ",
	"ヴ": "ウ",
}

def compile_ignorable_for_sort(chars: str) -> Pattern[str]:
	if not chars:
		return re.compile(r"(?!x)x")
	return re.compile("[" + re.escape(chars) + "]")

def kata_to_hira(text: str) -> str:
	out = []
	for ch in text:
		o = ord(ch)
		if 0x30A1 <= o <= 0x30F6:
			out.append(chr(o - 0x60))
		else:
			out.append(ch)
	return "".join(out)

def clean_kana_core(text: str, ignorable_for_sort: Pattern[str]) -> str:
	if text is None:
		return ""

	# (1) remove whitespace
	text = _WS_ANY.sub("", str(text))

	# (2) remove ignorable characters
	text = ignorable_for_sort.sub("", text)

	if not text:
		return ""

	# (3) normalize small kana -> full size
	text = text.translate(_SMALL_TO_BIG)

	# (4) remove voicing distinctions
	text = "".join(_SEION_MAP.get(ch, ch) for ch in text)

	return text

def prep_kana_for_sort(text: str, ignorable_for_sort: Pattern[str]) -> str:
	# sorting/grouping normalization:
	# core cleanup + script unification
	return kata_to_hira(clean_kana_core(text, ignorable_for_sort))

# Matrix for first-pass Kana sorting order
GOJUON_ROWS = [
	["ー"],
	["あ", "い", "う", "え", "お"],
	["か", "き", "く", "け", "こ"],
	["さ", "し", "す", "せ", "そ"],
	["た", "ち", "つ", "て", "と"],
	["な", "に", "ぬ", "ね", "の"],
	["は", "ひ", "ふ", "へ", "ほ"],
	["ま", "み", "む", "め", "も"],
	["や", "ゆ", "よ"],
	["ら", "り", "る", "れ", "ろ"],
	["わ", "ゐ", "ゑ", "を"],
	["ん"]
]

def gojuon_sort_key(kana: str, ignorable_for_sort: Pattern[str]) -> str:
	kana = prep_kana_for_sort(kana, ignorable_for_sort)

	def _rank(ch: str) -> Tuple[int, int, int]:
		for row_idx, row in enumerate(GOJUON_ROWS, start=1):
			if ch in row:
				return (row_idx, row.index(ch), 0)
		return (99, 99, ord(ch))

	ranks = [_rank(ch) for ch in kana]
	return "".join(f"{r:02d}{c:02d}{f:05d}" for (r, c, f) in ranks)[:240]

def headkey_from_kana(kana: str, ignorable_for_sort: Pattern[str]) -> str:
	k = prep_kana_for_sort(kana, ignorable_for_sort)
	return k[0] if k else ""

def headletter_from_kana(kana: str, ignorable_for_sort: Pattern[str], mode: str = "auto") -> str:
	k = clean_kana_core(kana, ignorable_for_sort)
	if not k:
		return ""

	ch = k[0]

	if mode == "hiragana":
		ch = kata_to_hira(ch)

	return ch

def normalize_head_char(ch: str) -> str:
	# small kana → big
	ch = _SMALL_TO_BIG.get(ch, ch)
	return ch

def get_headword(row, hmain: Dict[str, str]) -> str:
	kana2 = get_cell_semantic(row, hmain, H_KANA2)
	if kana2.strip():
		return kana2
	return get_cell_semantic(row, hmain, H_KANA)

# ------------
# Data model
# -----------
@dataclass
class Sense:
	jun: str
	meaning: str
	ruby: str
	comment: str
	examples_inline: str = "" # inline examples are already “terminal text”
	# relational examples: list of (src, jp)
	examples_rel: List[Tuple[str, str]] = field(default_factory=list)
	
@dataclass
class Entry:
	entry_id: str
	kana: str
	kana_sort: str
	head_key: str          # normalized grouping key
	head_letter: str       # displayed heading
	ipa: str
	pos: str
	rui: str
	para: str
	biko: str
	pitch: str
	senses: List[Sense]


# --------------
# Excel loading
# --------------
def read_sheet(excel_path: Path, sheet_name: str) -> pd.DataFrame:
	df = pd.read_excel(excel_path, sheet_name=sheet_name, dtype=str, keep_default_na=False, engine="openpyxl")
	return df

# -----------------------------
# Example sentence index (optional)
# -----------------------------

def build_rei_index(df_rei: pd.DataFrame, hex: Dict[str, str]) -> Dict[str, List[Tuple[str, str]]]:
	require_cols_semantic(df_rei, hex, [EX_MID, EX_KANA, EX_JPTRSL], "rei")

	out: Dict[str, List[Tuple[str, str]]] = {}

	for _, row in df_rei.iterrows():
		fval = get_cell_semantic(row, hex, EX_FILTER)
		if fval != "":
			continue	

		mid = get_cell_semantic(row, hex, EX_MID)
		src = get_cell_semantic(row, hex, EX_KANA)
		jp = get_cell_semantic(row, hex, EX_JPTRSL)

		# Skip rows lacking MEANING_ID or KANA
		if mid == "" or src == "":
			continue

		out.setdefault(mid, []).append((src, jp))

	return out

# ----------------
# Conversion core
# ----------------
def build_entries(
	df_main: pd.DataFrame,
	hmain: Dict[str, str],
	ignorable_for_sort: Pattern[str],
	headletter_mode: str = "auto",
	rei_index: Optional[Dict[str, List[Tuple[str, str]]]] = None
) -> List[Entry]:

	# Requires at least the ENTRY_ID and KANA_ORTHOGRAPHY columns 
	require_cols_semantic(df_main, hmain, [H_ID, H_KANA], "main")	
	entries: Dict[str, Entry] = {}

	for _, row in df_main.iterrows():
	
		# Skip row If filtered out
		fval = get_cell_semantic(row, hmain, H_FILTER)
		if fval != "":
				continue
		
		# Retrieve Entry ID and Kana orthography
		eid = get_cell_semantic(row, hmain, H_ID)
		kana = get_headword(row, hmain) # kana2 if present else kana
		
		# Skip row with empty EntryID or KANA
		if eid == "" or kana == "": 
			continue

		# Retrieve other values
		kana_sort = gojuon_sort_key(kana, ignorable_for_sort)  # the KANA string for sorting
		head_key = headkey_from_kana(kana, ignorable_for_sort) # normalized grouping key
		head_letter = headletter_from_kana(kana, ignorable_for_sort, headletter_mode) # displayed head letter
		
		ipa = get_cell_semantic(row, hmain, H_IPA)
		pos = get_cell_semantic(row, hmain, H_POS)
		rui = get_cell_semantic(row, hmain, H_RUI)
		para = get_cell_semantic(row, hmain, H_PARA)
		biko = get_cell_semantic(row, hmain, H_BIKO)
		pitch = get_cell_semantic(row, hmain, H_PITCH)

		jun = get_cell_semantic(row, hmain, H_ORDER)
		meaning = get_cell_semantic(row, hmain, H_MEANING)
		ruby = get_cell_semantic(row, hmain, H_RUBY)
		comment = get_cell_semantic(row, hmain, H_COM)


		# ----------------------------
		# Examples policy:
		# 1) If inline reibun exists -> use it verbatim (no splitting)
		# 2) Else if relational index exists -> use that
		# ----------------------------
		
		examples_inline = ""
		examples_rel: List[Tuple[str, str]] = []

		# Inline examples
		inline_rei = get_cell_semantic(row, hmain, H_REI)
		if inline_rei:
			examples_inline = inline_rei

		# Relational sheet
		elif rei_index is not None:
			key = get_cell_semantic(row, hmain, H_MID)
			if key in rei_index:
				examples_rel = rei_index[key]

		sense = Sense(jun=jun, meaning=meaning, ruby=ruby, comment=comment, examples_inline=examples_inline, examples_rel=examples_rel)

		# Add entry if first meaning encountered
		if eid not in entries:
			entries[eid] = Entry(
				entry_id=eid,
				kana=kana,
				kana_sort=kana_sort,
				head_key=head_key,
				head_letter=head_letter,
				ipa=ipa,
				pos=pos,
				rui=rui,
				para=para,
				biko=biko,
				pitch=pitch,
				senses=[sense],
			)
		# Add sense to an already picked up entry
		else:
			entries[eid].senses.append(sense)

	# sort senses by 順 when numeric
	for e in entries.values():
		def _jun_key(s: Sense) -> Tuple[int, str]:
			try:
				return (int(float(s.jun)), s.jun)
			except Exception:
				return (10**9, s.jun)
		e.senses = sorted(e.senses, key=_jun_key)

	return sorted(entries.values(), key=lambda e: (e.kana_sort, e.kana)) # Sorting logic


# -----------
# TeX output 
# -----------
def to_tex_entries(entries: List[Entry], profile: OrthoProfile, headletters: bool = True) -> str:
	lines: List[str] = []
	prev_head_key = None
	
	for e in entries:
		if headletters and e.head_key and e.head_key != prev_head_key:
			lines.append(r"\LetterHead{" + e.head_letter + r"}" + "\n")
			prev_head_key = e.head_key

		head_kvs: List[str] = []
		head_kvs.append(keyval_pair("kana", render_ryu(e.kana, profile)))		

		if e.ipa.strip():
			head_kvs.append(keyval_pair("ipa", render_jp_plain(e.ipa)))
		if e.pos.strip():
			head_kvs.append(keyval_pair("pos", render_jp_plain(e.pos)))
		if e.rui.strip():
			head_kvs.append(keyval_pair("rui", render_jp_plain(e.rui)))
		if e.para.strip():
			head_kvs.append(keyval_pair("para", render_ryu(e.para, profile))) # If Paradigm contains only Ryukyuan
		if e.pitch.strip():
			head_kvs.append(keyval_pair("acc", render_jp_plain(e.pitch)))

		head_kvs = [kv for kv in head_kvs if kv]
		head_opt = ",".join(head_kvs)

		meaning_lines: List[str] = []

		for s in e.senses:
			if s.ruby.strip():
				gloss = render_jp_ruby(s.ruby) # applies both ruby rules 
			else:
				gloss = render_jp_prose(s.meaning, profile)

			expl = render_jp_prose(s.comment, profile)

			if s.examples_inline.strip():
				examples = tex_rubyize_general(s.examples_inline) # need to apply to orthoprofile
			else:
				examples = "".join(
					r"\reibun{"
					+ render_ryu(src, profile) 
					+ r"}{"
					+ render_jp_prose(jp, profile) #ruby not properly working?
					+ r"}"
					for (src, jp) in (s.examples_rel or [])
				)

			meaning_lines.append(
				r"\ryumeaning%"
				+ "\n\t\t{" + gloss + r"}{"
				+ expl + r"}{"
				+ examples + r"}%"
			)

		meanings_block = (
			r"\MeaningsBlock{%"
			+ "\n\t"
			+ "\n\t".join(meaning_lines)
			+ "\n\t}%"
		)

		tail_kvs: List[str] = []

		if e.biko.strip():
			biko_tex = render_jp_prose(e.biko, profile)
			tail_kvs.append(keyval_pair("note", biko_tex))	
	
		tail_kvs = [kv for kv in tail_kvs if kv]
		tail_opt = ",".join(tail_kvs)

		entry_tex = (
			r"\entry"
			+ "\n\t{\\headPrint[" + head_opt + r"]}%"
			+ "\n\t{%\n\t\t" + meanings_block + "\n\t}%"
			+ "\n\t{\\tailPrint[" + tail_opt + r"]}%"
			+ "\n"
		)

		lines.append(entry_tex)

	return "".join(lines)

# --------------
# Reverse Index
# --------------

def to_tex_gyaku_jp2ryu(df_main: pd.DataFrame, hmain: Dict[str, str], profile: OrthoProfile, ignorable_for_sort: Pattern[str]) -> str:
	"""
	Generate Japanese→Ryukyuan reverse index:
	\rentry{JP-yomi}{JP-kanji}{Ryukyuan headwords}

	- Splits multiple JP items by "。"
	- Trims leading head markers like （...）
	- Deduplicates headwords per JP key
	- Sorts by yomi
	"""

	def F_ryu(x: str) -> str:
		return render_ryu(x, profile)

	def F_jp_prose(x: str) -> str:
		return render_jp_prose(x, profile)

	def F_jp_plain(x: str) -> str:
		return render_jp_plain(x)


	def trim_head(s: str) -> str:
		return re.sub(r'（.*?）(?P<a>.*?)', r'\g<a>', str(s))

	def split_items(s: str) -> List[str]:
		s = str(s or "")
		s = s[:-1] if s.endswith("。") else s
		return [p for p in s.split("。") if p != ""]

	# Collect: key = (kanji_trimmed, yomi_trimmed) -> {display_tex: raw_sort_source}
	out: Dict[Tuple[str, str], Dict[str, str]] = {}

	# store also a sort key for yomi
	sortkeys: Dict[Tuple[str, str], str] = {}

	# Require columns
	require_cols_semantic(df_main, hmain, [H_READING, H_MEANING, H_KANA], "main")

	errors: List[str] = []

	for _, row in df_main.iterrows():
		yomi_raw = get_cell_semantic(row, hmain, H_READING)
		kanji_raw = get_cell_semantic(row, hmain, H_MEANING)

		# Skip row then both 意味 and 読み empty
		if yomi_raw == "" and kanji_raw == "":
			continue

		headword = get_headword(row, hmain) # kana2 if present else kana
		if headword == "":
			continue

		# Apply Ryukyuan normalization
		headword_tex = F_ryu(headword)

		# Split JP items
		kanji_items = split_items(kanji_raw) if kanji_raw else []
		yomi_items = split_items(yomi_raw) if yomi_raw else []

		# Strict mirror check
		if len(kanji_items) != len(yomi_items):
			errors.append(
				f"Row {int(row.name)+2}: split count mismatch "
				f"(意味={len(kanji_items)}, 読み={len(yomi_items)}) "
				f"意味='{kanji_raw}' 読み='{yomi_raw}'"
			)
			continue  # skip this row entirely

		for k_item, y_item in zip(kanji_items, yomi_items):
			kanji_trim = trim_head(k_item)
			yomi_trim = trim_head(y_item)

			# derive a stable sort key for yomi
			yomi_sort = gojuon_sort_key(yomi_trim, ignorable_for_sort)

			key = (kanji_trim, yomi_trim)

			# Create bucket if needed
			if key not in out:
				out[key] = {}
				sortkeys[key] = yomi_sort

			# Head treated as Japanese prose with possibility of Ryukyuan embedding
			if re.match(r"^（(?P<a>.*?)）", str(k_item)):
				head = re.sub(r"^（(?P<a>.*?)）.*", r"\g<a>", str(k_item))
				head_tex = "〔" + F_jp_prose(head) + r"\ntilde{}" + "〕"
				headword_tex2 = head_tex + headword_tex
			else:
				headword_tex2 = headword_tex

			# Dedup by exact display TeX, but sort by raw headword only
			out[key][headword_tex2] = headword

	# Sort keys primarily by yomi_sort, then yomi itself
	items = list(out.keys())
	items.sort(key=lambda k: (sortkeys.get(k, ""), prep_kana_for_sort(k[1], ignorable_for_sort), k[1], k[0]))

	# Emit TeX
	lines: List[str] = []
	for (kanji_trim, yomi_trim) in items:
		# Decide whether to show kanji: show only if kanji != yomi
		kanji_out = kanji_trim if (kanji_trim != yomi_trim and kanji_trim != "") else ""

		# Sort displayed headwords by their raw headword source
		heads = list(out[(kanji_trim, yomi_trim)].items())  # [(display_tex, raw_sort_source), ...]
		heads.sort(key=lambda t: (gojuon_sort_key(t[1], ignorable_for_sort), t[1]))

		c = "、".join(display for display, _ in heads)
		lines.append(r"\rentry{" + F_jp_plain(yomi_trim) + r"}{" + F_jp_plain(kanji_out) + r"}{" + c + r"}")

	# Report errors
	if errors:
		raise ValueError("JP↔yomi segmentation errors:\n" + "\n".join(errors))

	return "\n".join(lines) + "\n"

# ----------
# Helper functions
# ----------

from datetime import datetime

# Output filename formatting
def make_outname(excel_path: Path, suffix: str) -> Path:
	stem = excel_path.stem
	date = datetime.now().strftime("%y%m%d")
	return excel_path.with_name(f"{stem}_{suffix}_{date}.tex")

# -------------------
# Command Line Input
# -------------------

def build_argparser() -> argparse.ArgumentParser:
	p = argparse.ArgumentParser(description="Convert Ryukyuan lexicographic data in the RyuTab format (.xlsx) to RyuTeX files.")
	p.add_argument("--settings", default="ryutex-settings.ini", help="Path to settings.ini")
	p.add_argument("-e", "--o-entries", action="store_true", help="Output dictionary entries")
	p.add_argument("-r", "--o-reverse", action="store_true", help="Output Japanese→Ryukyuan reverse index")
	return p

def main() -> int:
	
	# Parse the arguments from command line
	args = build_argparser().parse_args()

	# Error on no output selected
	if not args.o_entries and not args.o_reverse:
		raise SystemExit("Error: specify at least one of --o-entries or --o-reverse")

	# Load settings from the .ini file
	cfg = Settings()
	try:
		cfg, hmap, profile = load_settings(args.settings)
	except Exception as e:
		logging.error(f"Failed to load settings from '{args.settings}': {e}")
		return 2

	# Excel path
	excel_path = cfg.excel_path

	# Read the lexical data sheet from the Excel file
	try:
		df_main = read_sheet(excel_path, cfg.sheet_main)			
	except Exception as e:
		logging.error(f"Failed to read lexical sheet '{cfg.sheet_main}': {e}")
		return 2

	# Read entence example sheet if available
	rei_index = None

	if cfg.sheet_example:
		try:
			df_rei = read_sheet(excel_path, cfg.sheet_example)
		except Exception as e:
			logging.error(f"Failed to read example sheet '{cfg.sheet_example}': {e}")
			return 2

		rei_index = build_rei_index(df_rei, hmap.ex)

	# Build ignorable for sort regex
	ignorable_for_sort = compile_ignorable_for_sort(cfg.ignorable_for_sort)

	# Build entries from the main sheet
	entries = build_entries(
		df_main,
		hmap.main,
		ignorable_for_sort,
		headletter_mode=cfg.headletter_mode,
		rei_index=rei_index
	)

	# Output entries if -e
	if args.o_entries:
		tex_entries = to_tex_entries(entries, profile, cfg.headletters)
		out_entries = make_outname(excel_path, "entries")
		out_entries.write_text(tex_entries, encoding="utf-8")
		print(f"Wrote entries → {out_entries}")

	# Output reverse index if -r
	if args.o_reverse:
		tex_reverse = to_tex_gyaku_jp2ryu(df_main, hmap.main, profile, ignorable_for_sort)
		out_reverse = make_outname(excel_path, "reverse")
		out_reverse.write_text(tex_reverse, encoding="utf-8")
		print(f"Wrote reverse index → {out_reverse}")

	return 0

if __name__ == "__main__":
	raise SystemExit(main())
